### ISSUE TITLE
Problem during npm install

### ISSUE THREAD

**Issue by gvader** [stevelacy/msi-keyboard-gui#21]
I am on Ubuntu 16.10 with newest node.js. Had problem with build as below:

```
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/gvader/Projects/msi-keyboard-gui/node_modules/nslog
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by stephenlacy** [comment]
What are your versions:

```
node:
npm:
libusb:
```
I noticed this similar issue (error 127) https://github.com/nodejs/node-gyp/issues/223
I have not yet come across this error though.

**Comment by gvader** [comment]
Hi @stevelacy 

Thanks for quick anwser. Versions are as below:
```
libusb-0.1-4:amd64:  2:0.1.12-30
libusb-1.0-0:amd64:  2:1.0.20-1
libusb-dev:   2:0.1.12-30
npm:  3.5.2-0ubuntu4
nodejs:  4.2.6~dfsg-1ubuntu5
nodejs-dev:  4.2.6~dfsg-1ubuntu5
```

**Comment by stephenlacy** [comment]
Please install node v6+ as that is mosylikely the problem, then re-install the project's dependencies.
```
rm -rf node_modules && npm i
```
https://github.com/stevelacy/msi-keyboard-gui#nodejs-6-is-required

**Comment by stephenlacy** [comment]
Updates?

**Comment by stephenlacy** [comment]
Could you do this:
```
git pull
rm -rf node_modules
npm install
sudo npm start
```

**Comment by stephenlacy** [comment]
Just published a release: https://github.com/stevelacy/msi-keyboard-gui/releases/tag/0.1.3
Can you confirm that the binary does run correctly, and if not the errors it produces?
Thanks
