### ISSUE TITLE
Add support for msi gs65

### ISSUE THREAD

**Issue by thgn** [stevelacy/msi-keyboard-gui#53]
### Issue

Add support for msi gs65.

Executing:
```

$ sudo ./msi-keyboard-gui gives the output:

Error

cannot open device with vendor id 0x1770 and product id 0xff00
Did you try using sudo?
```

```

$ lsusb
Bus 001 Device 002: ID 1038:1122 SteelSeries ApS 
```

### System versions:

```
nodejs: nodejs-10.9.0-1
npm: 6.4.0
libusb: libusb-1.0.22-1
```

**Comment by stephenlacy** [comment]
Can you comment the output from this project? https://github.com/stevelacy/msi-keyboard-hid-test

That will show what node-hid is returning.

**Comment by thgn** [comment]
Sure

```

> dev 1038 / 1122 : usage_page:5a10, usage:6766
> dev 1038 / 1122 : usage_page:1, usage:0
> [ { vendorId: 4152,
>     productId: 4386,
>     path: '/dev/hidraw0',
>     serialNumber: '',
>     manufacturer: 'SteelSeries',
>     product: 'SteelSeries KLC',
>     release: 553,
>     interface: 0,
>     usagePage: 23056,
>     usage: 26470 },
>   { vendorId: 4152,
>     productId: 4386,
>     path: '/dev/hidraw1',
>     serialNumber: '',
>     manufacturer: 'SteelSeries',
>     product: 'SteelSeries KLC',
>     release: 553,
>     interface: 1,
>     usagePage: 1 } ]
```

**Comment by stephenlacy** [comment]
What happens when you swap the vendorId and productId here? https://github.com/stevelacy/msi-keyboard/blob/master/lib/findKeyboard.js#L8

**Comment by thgn** [comment]
You mean replace it like this?
```
module.exports = function() {
	var board = new hid.HID(4152, 4386);
```
Tried:
```

sudo npm install msi-keyboard

sudo msikeyboard
```
Before and After the changes I get:
```

$ sudo msikeyboard 
javier@archMsi1070 ~/msi-keyboard $ /usr/lib/node_modules/msi-keyboard-cli/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/Debug/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/Release/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/out/Debug/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/Debug/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/out/Release/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/Release/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/build/default/HID.node
 → /usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/compiled/10.9.0/linux/x64/HID.node
    at bindings (/usr/lib/node_modules/msi-keyboard-cli/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/msi-keyboard-cli/node_modules/node-hid/nodehid.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/msi-keyboard-cli/node_modules/msi-keyboard/lib/findKeyboard.js:1:73)

```

**Comment by stevelacy** [comment]
What is your node version?

**Comment by stephenlacy** [comment]
Oh, this is why: `/usr/lib/node_modules/msi-keyboard-cli` the msi-keyboard-cli is not my project.

You don't install it, you clone it:
```
git clone https://github.com/stevelacy/msi-keyboard
cd msi-keyboard
npm install
```
Then edit the files

**Comment by thgn** [comment]
Hi, I also tried yesterday git cloning and editing files with the same result :/. Is maybe  missing a dependency? I'm currently at work but I'll  post output at home.

**Comment by thgn** [comment]
```
sudo node blink.js 
[sudo] password for javier: 
/home/javier/msi-keyboard/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/javier/msi-keyboard/node_modules/node-hid/build/HID.node
 → /home/javier/msi-keyboard/node_modules/node-hid/build/Debug/HID.node
 → /home/javier/msi-keyboard/node_modules/node-hid/build/Release/HID.node
 → /home/javier/msi-keyboard/node_modules/node-hid/out/Debug/HID.node
 → /home/javier/msi-keyboard/node_modules/node-hid/Debug/HID.node
 → /home/javier/msi-keyboard/node_modules/node-hid/out/Release/HID.node
 → /home/javier/msi-keyboard/node_modules/node-hid/Release/HID.node
 → /home/javier/msi-keyboard/node_modules/node-hid/build/default/HID.node
 → /home/javier/msi-keyboard/node_modules/node-hid/compiled/10.9.0/linux/x64/HID.node
    at bindings (/home/javier/msi-keyboard/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/home/javier/msi-keyboard/node_modules/node-hid/nodehid.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/javier/msi-keyboard/lib/findKeyboard.js:1:73)

```

**Comment by stephenlacy** [comment]
Did npm install complete without errors?

**Comment by thgn** [comment]
I would say so...
```

sudo npm install
added 23 packages from 439 contributors and audited 2246 packages in 2.401s
found 0 vulnerabilities

```

**Comment by stephenlacy** [comment]
try it without sudo, so first remove them with `sudo rm -rf node_modules` and then `npm install`

**Comment by thgn** [comment]
OK, I somehow  had screwed up npm. I deleted all configs (also I had a wrong  owner of node_modules in my home dir), removed msi-keyboard npm installed project and then reinstalled everything (included git cloning again).

Apparently I no longer have those errors, sorry for wasting your time I'm not very use to npm.

If I understood correctly from previous message you wanted to test the file lib/findkeyboard.js with the line:
`	var board = new hid.HID(4152, 4386);`
Now I get these error output.

**Before** changing:
```
sudo node blink.js 
/home/javier/node_modules/node-hid/nodehid.js:54
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

Error: cannot open device with vendor id 0x1770 and product id 0xff00
    at new HID (/home/javier/node_modules/node-hid/nodehid.js:54:17)
    at module.exports (/home/javier/msi-keyboard/lib/findKeyboard.js:8:14)
    at Object.<anonymous> (/home/javier/msi-keyboard/examples/blink.js:1:92)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
```

**After** modifying I don't get any visible output in console or effect in the keyboard, I don't get the cursor back either.

**Comment by stephenlacy** [comment]
Sounds like the new keyboard is using a different hid interface.

The only way to support the new keyboard is to reverse engineer the new steelseries controller on windows, determine what it is sending to the HID device, and clone that. I do not have the new keyboard, and would need to rely on an owner of a new device who is capable of reverse engineering the new controller.

**Comment by dfredell** [comment]
@stevelacy 

I have never developed at the driver/ USB layer before. I was thinking of giving it a shot. I just picked up a MSI GS63 8RE laptop. It has a steelseries keyboard with vendor id 0x1770 and product id 0xff00. In my free time I was going to try and code up a controller for my keyboard. I have used wireshark to capture some USB packets getting sent to the keyboard. I figured that might be a good start, unless you got a better idea?

[keyboard msi GS63 8RE.zip](https://github.com/stevelacy/msi-keyboard-gui/files/2395182/keyboard.msi.GS63.8RE.zip)

**Comment by stephenlacy** [comment]
This document goes over collecting and reverse engineering with usbpcap: https://github.com/charlysan/pyrfidhid/wiki/Reverse-Engineering-A-USB-HID-RFID-Reader-Writer
I looked at the packets capture and it seems that usbpcap might have split the requests into two instead of just the feature report with data.

**Comment by dfredell** [comment]
I just found https://github.com/Askannz/msi-perkeyrgb#branch=master via https://wiki.archlinux.org/index.php/MSI_GS65#Lights and it worked as is. So, I will just use that.

**Comment by stephenlacy** [comment]
You could port this to node since you have access to the keyboard: https://github.com/Askannz/msi-perkeyrgb/blob/master/msi_perkeyrgb/protocol.py

**Comment by neumartin** [comment]
Any update for GS65?

**Comment by stephenlacy** [comment]
No — I do not have a GS65 or access to one, thus I will close this issue
